name: tradeit_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  # Gerenciamento de estado e DI
  flutter_riverpod: ^2.5.1

  # Firebase (autenticação e banco de dados)
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.5

  # Ícones e imagens de rede
  cached_network_image: ^3.3.1
  image_picker: ^1.0.7
  http: ^1.2.1

  # Outros úteis
  equatable: ^2.0.5
  intl: ^0.18.1

  # localização
  geolocator: ^11.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png    
  # fonts:
  # - family: Montserrat
  #   fonts:
  #     - asset: assets/fonts/Montserrat-Regular.ttf



